call "Wix Installer Build MM EC_GAC_30.bat"
call "Wix Installer Build MM EcFolderACLs.bat"
call "Wix Installer Build MM ICU040.bat"
call "Wix Installer Build MM ICUECHelp.bat"
call "Wix Installer Build MM Managed Install Fix.bat"
call "Wix Installer Build MM MS KB908002 Fix.bat"
call "Wix Installer Build MM Old C++ and MFC DLLs.bat"
call "Wix Installer Build MM PerlEC.bat"
call "Wix Installer Build MM PythonEC.bat"
call "Wix Installer Build MM SetPath.bat"
