del "Managed Install Fix.mmp.wxs.log"
del "WixLinkManaged Install Fix.log"
ProcessWixMMs.js "Managed Install Fix.mm.wxs"
candle -nologo "Managed Install Fix.mmp.wxs" -sw1044 >"Managed Install Fix.mmp.wxs.log"
light -nologo "Managed Install Fix.mmp.wixobj" -out "Managed Install Fix.msm" >"WixLinkManaged Install Fix.log"
